package dml.user.repository;

import dml.largescaletaskmanagement.entity.CompleteSegmentIfTimeout;
import dml.largescaletaskmanagement.repository.SegmentProcessingTimeoutHandlingStrategyRepository;

public interface ClearSessionTaskSegmentTimeoutStrategyRepository extends SegmentProcessingTimeoutHandlingStrategyRepository<CompleteSegmentIfTimeout> {
}
